-- Add new columns to Accused
ALTER TABLE Accused ADD COLUMN Nationality VARCHAR(50) DEFAULT 'Indian';
ALTER TABLE Accused ADD COLUMN Status VARCHAR(50) DEFAULT 'At Large';
ALTER TABLE Accused ADD COLUMN Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add new columns to Suspects
ALTER TABLE Suspects ADD COLUMN Nationality VARCHAR(50) DEFAULT 'Indian';
ALTER TABLE Suspects ADD COLUMN Status VARCHAR(50) DEFAULT 'Under Surveillance';
ALTER TABLE Suspects ADD COLUMN Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Update FIR_Accused
ALTER TABLE FIR_Accused DROP CONSTRAINT fir_accused_pkey;
ALTER TABLE FIR_Accused ADD COLUMN FIR_Accused_ID SERIAL PRIMARY KEY;
ALTER TABLE FIR_Accused ADD COLUMN Role_In_Crime VARCHAR(200);
ALTER TABLE FIR_Accused ADD COLUMN Date_Linked TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE FIR_Accused ADD CONSTRAINT unique_fir_accused UNIQUE (FIR_ID, Accused_ID);

-- Update FIR_Suspects
ALTER TABLE FIR_Suspects DROP CONSTRAINT fir_suspects_pkey;
ALTER TABLE FIR_Suspects ADD COLUMN FIR_Suspects_ID SERIAL PRIMARY KEY;
ALTER TABLE FIR_Suspects ADD COLUMN Reason_For_Suspicion TEXT;
ALTER TABLE FIR_Suspects ADD COLUMN Date_Linked TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE FIR_Suspects ADD CONSTRAINT unique_fir_suspects UNIQUE (FIR_ID, Suspect_ID);
